Repository buildo/eslint-plugin-fp-ts, pull requests merged in 2021-01, with the labels that each got.

#4 Add installation section
  README.md
  ci/pipeline.yml
Labels: WIP

#5 Report deprecation message for pipeable
  src/rules/no-pipeable.ts
  tests/rules/no-pipeable.test.ts
Labels: WIP

#6 Fix tsc compilation
  tsconfig.json
Labels: WIP

#7 Add prefer-traverse
  README.md
  docs/rules/prefer-traverse.md
  package.json
  src/index.ts
  src/rules/prefer-traverse.ts
  src/utils.ts
  tests/rules/prefer-traverse.test.ts
  yarn.lock
Labels: WIP

#10 Add no-redundant-flow
  README.md
  docs/rules/no-redundant-flow.md
  src/index.ts
  src/rules/no-redundant-flow.ts
  src/utils.ts
  tests/rules/no-pipeable.test.ts
  tests/rules/no-redundant-flow.test.ts
Labels: WIP

#15 Fix typo
  docs/rules/no-redundant-flow.md
Labels: WIP

#14 Add prefer-chain
  docs/rules/prefer-chain.md
  src/index.ts
  src/rules/prefer-chain.ts
  src/rules/prefer-traverse.ts
  src/utils.ts
  tests/rules/prefer-chain.test.ts
Labels: WIP

#18 Add prefer-chain to readme
  README.md
Labels: WIP

#19 Add fp-ts and eslint
  .eslintrc.json
  .github/release-drafter.yml
  ci/tasks/test.sh
  package.json
  src/rules/prefer-chain.ts
  src/rules/prefer-traverse.ts
  src/utils.ts
  yarn.lock
Labels: WIP, chore

#20 Add config presets
  README.md
  src/index.ts
Labels: WIP

#21 Fix config export
  src/index.ts
Labels: WIP

#26 Add saner defaults for all configuration
  src/index.ts
Labels: WIP

#27 Use fp-ts/all configuration
  .eslintrc.json
  package.json
  yarn.lock
Labels: WIP

#29 Add no-module-imports
  README.md
  docs/rules/no-module-imports.md
  package.json
  src/index.ts
  src/rules/no-lib-imports.ts
  src/rules/no-module-imports.ts
  src/rules/no-redundant-flow.ts
  src/rules/prefer-chain.ts
  src/rules/prefer-traverse.ts
  src/utils.ts
  tests/rules/no-module-imports.test.ts
  tsconfig.json
  yarn.lock
Labels: WIP

#30 Several improvements to no-module-imports
  docs/rules/no-module-imports.md
  src/index.ts
  src/rules/no-module-imports.ts
  src/utils.ts
  tests/rules/no-module-imports.test.ts
Labels: WIP

#31 Use createRule utility for all rules
  src/index.ts
  src/rules/no-lib-imports.ts
  src/rules/no-pipeable.ts
  src/rules/no-redundant-flow.ts
  src/rules/prefer-chain.ts
  src/rules/prefer-traverse.ts
  tests/rules/no-lib-imports.test.ts
  tests/rules/no-pipeable.test.ts
  tests/rules/no-redundant-flow.test.ts
  tests/rules/prefer-chain.test.ts
  tests/rules/prefer-traverse.test.ts
Labels: WIP, chore

#32 Add prefer-bimap
  README.md
  docs/rules/prefer-bimap.md
  src/index.ts
  src/rules/prefer-bimap.ts
  src/utils.ts
  tests/rules/prefer-bimap.test.ts
Labels: WIP

#33 Upgrade eslint-plugin-fp-ts
  .eslintrc.json
  yarn.lock
Labels: WIP, chore

#34 Fix rule doc
  docs/rules/prefer-bimap.md
Labels: waiting for merge

#35 no-lib-imports preserve quotes
  src/rules/no-lib-imports.ts
  tests/rules/no-lib-imports.test.ts
Labels: waiting for merge

#41 add badges
  README.md
Labels: waiting for merge

#46 Replace astring with recast
  package.json
  src/utils.ts
  yarn.lock
Labels: WIP

#48 Fix matching of adjacent combinators
  src/utils.ts
  tests/rules/prefer-bimap.test.ts
Labels: WIP
